### PR TITLE
Sprint2 canvas drag

### PR DESCRIPTION
**Pull request by dantheman8300**
This PR has the current integration of the page layout component, minus the header component. The PR also has the drag and drop functionality for creating/modifying the molecules.

### CODE REVIEW

**Review by anthonynbui — COMMENTED** [review]
LGTM

**Review by tyherzog — APPROVED** [review]
LGTM!

**Review by eliseemelia — APPROVED** [review]
LGTM !

**Comment by anthonynbui** [comment]
LFGTM!

**Review by anthonynbui — APPROVED** [review]
LGTM for real

**Pull request merged**
