### PR TITLE
Sprint2 canvas snapping

### PR DESCRIPTION
**Pull request by tyherzog**
Implements relative coordinate system including hard coded buttons to test implementation.
Relative coordinates are generated in a tree like structure with the root molecule being located at the end of a drag event
Every other coordinate is generated relative to the root.

### CODE REVIEW

**Comment by anthonynbui** [comment]
LGTM!

**Review by eliseemelia — APPROVED** [review]
LGTM

**Review by dantheman8300 — APPROVED** [review]
LGTM 👍

**Review by anthonynbui — COMMENTED** [review]
LGTM

**Pull request merged**
